/**
 * @file aud_daisysp_permissive.h
 * @brief MIT/permissive DaisySP-derived modules; excludes DaisySP-LGPL ports.
 */
#ifndef AUD_DAISYSP_PERMISSIVE_H
#define AUD_DAISYSP_PERMISSIVE_H

#include "aud_dsp.h"
#include "aud_phasor.h"
#include "aud_adenv.h"
#include "aud_adsr.h"
#include "aud_svf.h"
#include "aud_onepole.h"
#include "aud_soap.h"
#include "aud_limiter.h"
#include "aud_crossfade.h"
#include "aud_osc.h"
#include "aud_oscillatorbank.h"
#include "aud_fm2.h"
#include "aud_formantosc.h"
#include "aud_variablesawosc.h"
#include "aud_variableshapeosc.h"
#include "aud_vosim.h"
#include "aud_zoscillator.h"
#include "aud_harmonic_osc.h"
#include "aud_chorus.h"
#include "aud_flanger.h"
#include "aud_phaser.h"
#include "aud_tremolo.h"
#include "aud_overdrive.h"
#include "aud_wavefolder.h"
#include "aud_autowah.h"
#include "aud_pitchshifter.h"
#include "aud_decimator.h"
#include "aud_sampleratereducer.h"
#include "aud_whitenoise.h"
#include "aud_clockednoise.h"
#include "aud_dust.h"
#include "aud_fractal_noise.h"
#include "aud_grainlet.h"
#include "aud_particle.h"
#include "aud_smooth_random.h"
#include "aud_samplehold.h"
#include "aud_karplusstring.h"
#include "aud_resonator.h"
#include "aud_modalvoice.h"
#include "aud_stringvoice.h"
#include "aud_drip.h"
#include "aud_analogbassdrum.h"
#include "aud_analogsnaredrum.h"
#include "aud_synthbassdrum.h"
#include "aud_synthsnaredrum.h"
#include "aud_hihat.h"
#include "aud_granularplayer.h"
#include "aud_dcblock.h"
#include "aud_delayline.h"
#include "aud_metro.h"
#include "aud_looper.h"
#include "aud_maytrig.h"

#endif
