/**
 * Copy the relevant fragments into CubeMX USER CODE sections. This file is
 * intentionally not part of the standalone library build because `hsai_BlockA1`
 * and `hsai_BlockB1` are generated by CubeMX.
 */
#include "aud_mcu_fx_chain.h"
#include "aud_mcu_sai_dma.h"

#define AUDIO_HALF_FRAMES 64u
#define AUDIO_DELAY_SAMPLES 24000u

__attribute__((section(".AudioDmaBuffer"), aligned(32)))
static int32_t audio_rx[2u * AUDIO_HALF_FRAMES * 2u];
__attribute__((section(".AudioDmaBuffer"), aligned(32)))
static int32_t audio_tx[2u * AUDIO_HALF_FRAMES * 2u];

static float audio_work[AUDIO_HALF_FRAMES * 2u];
__attribute__((section(".AudioDspState"), aligned(32)))
static float delay_left[AUDIO_DELAY_SAMPLES];
__attribute__((section(".AudioDspState"), aligned(32)))
static float delay_right[AUDIO_DELAY_SAMPLES];
static AudMcuFxChain fx;
static AudMcuAudio audio;
static AudMcuSaiDma sai_dma;

/* Call after MX_SAI1_Init(), MX_DMA_Init() and codec register setup. */
int AudioPlatform_Start(SAI_HandleTypeDef *rx, SAI_HandleTypeDef *tx)
{
    if (AudMcuFxChain_Init(&fx, 48000.0f, delay_left, delay_right,
                           AUDIO_DELAY_SAMPLES) != 0) {
        return -1;
    }
    if (AudMcuAudio_Init(&audio, audio_work, AUDIO_HALF_FRAMES * 2u,
                         AUDIO_HALF_FRAMES, AUD_MCU_PCM_S24_LEFT,
                         AudMcuFxChain_Process, &fx) != 0) {
        return -1;
    }
    if (AudMcuSaiDma_Init(&sai_dma, rx, tx, &audio, audio_rx, audio_tx,
                          AUDIO_HALF_FRAMES) != 0) {
        return -1;
    }
    return AudMcuSaiDma_Start(&sai_dma);
}

void HAL_SAI_RxHalfCpltCallback(SAI_HandleTypeDef *hsai)
{
    if (hsai == sai_dma.rx_sai) {
        AudMcuSaiDma_OnRxHalfComplete(&sai_dma);
    }
}

void HAL_SAI_RxCpltCallback(SAI_HandleTypeDef *hsai)
{
    if (hsai == sai_dma.rx_sai) {
        AudMcuSaiDma_OnRxComplete(&sai_dma);
    }
}
