set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)

set(CMAKE_C_FLAGS_INIT "-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard")

if(DEFINED ENV{AUD_MPU_SYSROOT} AND NOT "$ENV{AUD_MPU_SYSROOT}" STREQUAL "")
  set(CMAKE_SYSROOT "$ENV{AUD_MPU_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH "$ENV{AUD_MPU_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
